# --- BẮT ĐẦU NỘI DUNG SỬA LỖI ---

baseURL = "https://unvianpetronas.github.io/fcj-workshop/"
relativeURLs = false
canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "workshop"
# Git hub repo link
editURL = ""
description = ""
author = "unviantruong.com"
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false

[Languages]
[Languages.en]
title = "Internship Report"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[Languages.vi]
title = "Báo cáo thực tập"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

# Bổ sung các mục menu chính cho phiên bản Tiếng Việt (Phần bị thiếu)
[[languages.vi.menu.main]]
name = "Nhật ký công việc"
identifier = "Worklog"
weight = 10
[[languages.vi.menu.main]]
name = "Đề xuất"
identifier = "Proposal"
weight = 20
[[languages.vi.menu.main]]
name = "Blog đã dịch"
identifier = "BlogsTranslated"
weight = 30
[[languages.vi.menu.main]]
name = "Sự kiện tham gia"
identifier = "EventParticipated"
weight = 40
[[languages.vi.menu.main]]
name = "Workshop"
identifier = "Workshop"
weight = 50
[[languages.vi.menu.main]]
name = "Tự đánh giá"
identifier = "Self-evaluation"
weight = 60
[[languages.vi.menu.main]]
name = "Phản hồi"
identifier = "Feedback"
weight = 70

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# --- KẾT THÚC NỘI DUNG ĐÃ SỬA ---